excluded_categories:
  type: list
  default: ""
  description:
    en: "List of excluded category slugs"
order_by_activity:
  type: list
  default: ""
  description:
    en: "Categories where children are ordered by activity"
show_latest:
  type: list
  default: ""
  description:
    en: "Categories to show latest (unread + new) topic counts for"